# Generated by Django 3.1.2 on 2020-11-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201128_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfilecontent',
            old_name='file',
            new_name='files',
        ),
    ]
