# Generated by Django 3.1.2 on 2020-11-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201128_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfilecontent',
            old_name='files',
            new_name='file',
        ),
    ]
