# Generated by Django 3.1.2 on 2020-11-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path', verbose_name='profile_picture'),
        ),
    ]
